
package view;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import utilities.JTextFieldLimit;


/**
 *
 * @author Rawan
 */
public class frm_IPhoneBook extends javax.swing.JFrame {

    //***************************************** Variables *********************************************
    /**Login approval*/
    private boolean loginApproved = false;
    /**Flag variable*/
    private int flag = 0;
    /**ViewLogic field*/
    private static View view;
    /**
     * Creates new form frm_IPhoneBook
     * @param view
     */
    public frm_IPhoneBook(View view) {
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
                    e.getMessage();
            try {
                UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                ex.getMessage();
            }
        }
        getContentPane().setBackground( new Color(182,184,192) );
        frm_IPhoneBook.view = view;
        initComponents();
        fillTable();
        lblMessage.setForeground(Color.red);
        tblPhoneBook.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        txtStartPhoneNumber.setDocument(new JTextFieldLimit(3));
        txtEndPhoneNumber.setDocument(new JTextFieldLimit(7));
        setVisible(true);
        setResizable(false);
        setLocationRelativeTo(null);
        addWindowListener(new MyWindowListener());
     
    }

    private void fillTable() {
    DefaultTableModel model = (DefaultTableModel) tblPhoneBook.getModel();
    String start;
    String end; 
 }

public class MyWindowListener extends WindowAdapter {

        @Override
        public void windowClosing(WindowEvent e) {
            int question = JOptionPane.showConfirmDialog(null, "Save changes before exit?", "Save", JOptionPane.YES_NO_CANCEL_OPTION);
            if (question == JOptionPane.NO_OPTION) { // if user clicked NO, exit
                System.exit(0);
            }
            if (question == JOptionPane.YES_OPTION) { // if clicked YES, try to save his data
                try {
                    view.executeSysExit(false);
                    
                } catch (IOException ex) {
                    
                }
            }

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhoneBook = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtStartPhoneNumber = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnMod = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtEndPhoneNumber = new javax.swing.JTextField();
        lblMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblPhoneBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Phone Number", "First Name", "Last Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPhoneBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhoneBookMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPhoneBook);

        jLabel1.setText("First Name:");

        jLabel2.setText("Last Name:");

        jLabel4.setText("Phone Number:");

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        btnAdd.setText("Add New");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnMod.setText("Modify");
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel3.setText("-");

        lblMessage.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(18, 18, 18)
                                .addComponent(btnMod)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtFirstName)
                                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtStartPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEndPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEndPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtStartPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnMod)
                    .addComponent(btnDelete))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        lblMessage.setText("");
        DefaultTableModel model = (DefaultTableModel) tblPhoneBook.getModel();
        if(tblPhoneBook.getSelectedRow()==-1){
            if(tblPhoneBook.getRowCount()==0){
                lblMessage.setText("Table is empty!");
            }
            else{
                lblMessage.setText("You must select a contact!");
            }
        }
        else{
            view.deleteTuple(txtStartPhoneNumber, txtEndPhoneNumber, model, tblPhoneBook);
            view.clearFields(txtStartPhoneNumber, txtEndPhoneNumber, txtFirstName, txtLastName);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        lblMessage.setText("");
        DefaultTableModel model = (DefaultTableModel) tblPhoneBook.getModel();
         if(txtFirstName.getText().trim().equals("") || txtLastName.getText().trim().equals("") || txtStartPhoneNumber.getText().trim().equals("") || txtEndPhoneNumber.getText().trim().equals("")){
             lblMessage.setText("Please fill all fields");
         }
         else {
             if(txtStartPhoneNumber.getText().length() == 2 || txtStartPhoneNumber.getText().length() == 3 && txtEndPhoneNumber.getText().length() == 7 ){
                view.addTuple(txtStartPhoneNumber, txtEndPhoneNumber, txtFirstName, txtLastName, model);
             }
             else{
                 lblMessage.setText("Phone number format must be: XX-XXXXXXX or XXX-XXXXXXXX");
             }
         }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        lblMessage.setText("");
        DefaultTableModel model = (DefaultTableModel) tblPhoneBook.getModel();
        if(tblPhoneBook.getSelectedRow()==-1){
            if(tblPhoneBook.getRowCount()==0){
                lblMessage.setText("Table is empty!");
            }
            else{
                lblMessage.setText("You must select a contact!");
            }
        }
        else{
                     if(txtFirstName.getText().trim().equals("") || txtLastName.getText().trim().equals("") || txtStartPhoneNumber.getText().trim().equals("") || txtEndPhoneNumber.getText().trim().equals("")){
             lblMessage.setText("Please fill all fields");
         }
         else {
                if(txtStartPhoneNumber.getText().length() == 2 || txtStartPhoneNumber.getText().length() == 3 && txtEndPhoneNumber.getText().length() == 7 ){
                   view.modifyTuple(txtStartPhoneNumber, txtEndPhoneNumber, txtFirstName, txtLastName, model.getValueAt(tblPhoneBook.getSelectedRow(), 0).toString(),model, tblPhoneBook);

                }
                else{
                    lblMessage.setText("Phone number format must be: XX-XXXXXXX or XXX-XXXXXXXX");
                }
            }
        }
    }//GEN-LAST:event_btnModActionPerformed

    private void tblPhoneBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhoneBookMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblPhoneBook.getModel();
        String phone = model.getValueAt(tblPhoneBook.getSelectedRow(), 0).toString();
        String start;
        String end;
        if(phone.length() == 11){ // if the format number is: "052" , etc..
            start = phone.substring(0, 3);
            end = phone.substring(4);
        }
        else { // else the format number is: "04" , etc..
            start = phone.substring(0, 2);
            end = phone.substring(3);
        }
        txtStartPhoneNumber.setText(start);
        txtEndPhoneNumber.setText(end);
        txtFirstName.setText(model.getValueAt(tblPhoneBook.getSelectedRow(), 1).toString());
        txtLastName.setText(model.getValueAt(tblPhoneBook.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_tblPhoneBookMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frm_IPhoneBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frm_IPhoneBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frm_IPhoneBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frm_IPhoneBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frm_IPhoneBook().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTable tblPhoneBook;
    private javax.swing.JTextField txtEndPhoneNumber;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtStartPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
