/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Cursor;
import java.awt.Dimension;
import static java.awt.Toolkit.getDefaultToolkit;
import java.util.Arrays;
import static utilities.Constants.INFO_ICON_PATH;

/**
 * Information and Game rules frame for the game.
 *
 * @author BGS Team
 */
public class InfoFrame extends javax.swing.JFrame {

    /**
     * ViewLogic field
     */
    private final View view;

    /**
     * Creates new form NewJFrame
     * @param view
     */
    public InfoFrame(View view) {
        this.view = view;
        initComponents();
        setLocationRelativeTo(null);
        txtaRulesArea.setEditable(false);
        setIconImage(getDefaultToolkit().getImage(getClass().getResource(INFO_ICON_PATH)));
        btnClose.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCopyrights = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        txtaRulesArea = new javax.swing.JTextArea();
        pnlHeader = new javax.swing.JPanel();
        lblRulesTitle = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        lblCopyrights.setBackground(new java.awt.Color(255, 255, 255));
        lblCopyrights.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCopyrights.setText("©2014 Blackjack Game System (BGS™)");

        txtaRulesArea.setEditable(false);
        txtaRulesArea.setColumns(1);
        txtaRulesArea.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtaRulesArea.setLineWrap(true);
        txtaRulesArea.setRows(35);
        txtaRulesArea.setText(Arrays.toString(view.getRules()));
        txtaRulesArea.setWrapStyleWord(true);
        txtaRulesArea.setAutoscrolls(false);
        txtaRulesArea.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtaRulesArea.setMaximumSize(new java.awt.Dimension(400, 300));
        txtaRulesArea.setMinimumSize(new java.awt.Dimension(400, 300));
        txtaRulesArea.setPreferredSize(new Dimension(400, 200));
        jScrollPane.setViewportView(txtaRulesArea);

        pnlHeader.setLayout(null);

        lblRulesTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/titleInfo.png"))); // NOI18N
        lblRulesTitle.setToolTipText("");
        lblRulesTitle.setAlignmentY(0.0F);
        lblRulesTitle.setIconTextGap(0);
        pnlHeader.add(lblRulesTitle);
        lblRulesTitle.setBounds(0, 0, 400, 133);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCopyrights, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCopyrights, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        view.playSound("Button");
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblCopyrights;
    private javax.swing.JLabel lblRulesTitle;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JTextArea txtaRulesArea;
    // End of variables declaration//GEN-END:variables
}
