
package view;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import utilities.Constants;

/**
 * MainFrame frame for the game.
 * @author BGS Team
 */
public class MainFrame extends javax.swing.JFrame {

    //***************************************** Variables *********************************************
    /**Login approval*/
    private boolean loginApproved = false;
    /**Flag variable*/
    private int flag = 0;
    /**ViewLogic field*/
    private static View view;
    private Image image;
    boolean firstTimeNameType = true;
    boolean firstTimePassType = true;
    
    
    /**
     * Creates new form MainFrame
     * @param view
     */
    public MainFrame(View view) {
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
                    e.getMessage();
            try {
                UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                ex.getMessage();
            }
        }
        getContentPane().setBackground( new Color(182,184,192) );
        MainFrame.view = view;
        initComponents();
        
        btnSubmit.setContentAreaFilled(false);
        btnSitDown.setVisible(false);
        pnlFacts.setVisible(false);
        setVisible(true);
        setResizable(false);
        setLocationRelativeTo(null);
        addWindowListener(new MyWindowListener());
        pnlLogin.setOpaque(false);     
    }

    public class MyWindowListener extends WindowAdapter {

        @Override
        public void windowClosing(WindowEvent e) {
            int question = JOptionPane.showConfirmDialog(null, "Save changes before exit?", "Save", JOptionPane.YES_NO_CANCEL_OPTION);
            if (question == JOptionPane.NO_OPTION) { // if user clicked NO, exit
                System.exit(0);
            }
            if (question == JOptionPane.YES_OPTION) { // if clicked YES, try to save his data
                try {
                    view.executeSysExit(false);
                } catch (IOException ex) {
                    if (Constants.DEBUG){
                        System.out.println(ex.getMessage());
                    }
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFacts = new javax.swing.JPanel();
        lblFactsTitle = new javax.swing.JLabel();
        lblFactsText = new javax.swing.JLabel();
        lblBgFacts = new javax.swing.JLabel();
        pnlLogin = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtfName = new javax.swing.JTextField();
        txtfPassword = new javax.swing.JPasswordField();
        btnSubmit = new javax.swing.JButton();
        lblError = new javax.swing.JLabel("<html>** You may login your last used name or just register a new one.</html>");
        btnSitDown = new javax.swing.JButton();
        pnlScoreBoard = new javax.swing.JPanel();
        lblScoreBoard = new javax.swing.JLabel();
        pnlBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        pnlFacts.setOpaque(false);

        lblFactsTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFactsTitle.setForeground(new java.awt.Color(204, 204, 204));
        lblFactsTitle.setText("Did you know?");

        lblFactsText.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        lblFactsText.setForeground(new java.awt.Color(204, 204, 204));
        lblFactsText.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lblBgFacts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bgFacts.png"))); // NOI18N

        javax.swing.GroupLayout pnlFactsLayout = new javax.swing.GroupLayout(pnlFacts);
        pnlFacts.setLayout(pnlFactsLayout);
        pnlFactsLayout.setHorizontalGroup(
            pnlFactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFactsLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlFactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFactsText, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFactsTitle))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(pnlFactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblBgFacts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFactsLayout.setVerticalGroup(
            pnlFactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFactsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblFactsTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFactsText, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlFactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblBgFacts, javax.swing.GroupLayout.PREFERRED_SIZE, 108, Short.MAX_VALUE))
        );

        getContentPane().add(pnlFacts);
        pnlFacts.setBounds(30, 40, 390, 100);

        pnlLogin.setOpaque(false);

        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setText("Login:");

        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Player Name:");

        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password:");

        txtfName.setForeground(new java.awt.Color(102, 102, 102));
        txtfName.setText("Your name");
        txtfName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfNameKeyPressed(evt);
            }
        });

        txtfPassword.setForeground(new java.awt.Color(102, 102, 102));
        txtfPassword.setText("Password");
        txtfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfPasswordKeyPressed(evt);
            }
        });

        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/gameButton_Submit.png"))); // NOI18N
        btnSubmit.setContentAreaFilled(false);
        btnSubmit.setMaximumSize(new java.awt.Dimension(154, 39));
        btnSubmit.setMinimumSize(new java.awt.Dimension(154, 39));
        btnSubmit.setPreferredSize(new java.awt.Dimension(154, 39));
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubmitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSubmitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSubmitMouseReleased(evt);
            }
        });
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblError.setForeground(new java.awt.Color(153, 255, 255));
        lblError.setPreferredSize(new java.awt.Dimension(185, 60));

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLogin)
                            .addGroup(pnlLoginLayout.createSequentialGroup()
                                .addComponent(lblName)
                                .addGap(18, 18, 18)
                                .addComponent(txtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlLoginLayout.createSequentialGroup()
                                .addComponent(lblPassword)
                                .addGap(32, 32, 32)
                                .addComponent(txtfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblLogin)
                .addGap(18, 18, 18)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblName))
                    .addComponent(txtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblPassword))
                    .addComponent(txtfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pnlLogin);
        pnlLogin.setBounds(10, 440, 200, 230);

        btnSitDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/gameButton_SitDown.png"))); // NOI18N
        btnSitDown.setContentAreaFilled(false);
        btnSitDown.setMaximumSize(new java.awt.Dimension(154, 39));
        btnSitDown.setMinimumSize(new java.awt.Dimension(154, 39));
        btnSitDown.setPreferredSize(new java.awt.Dimension(154, 39));
        btnSitDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSitDownMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSitDownMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSitDownMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSitDownMouseReleased(evt);
            }
        });
        btnSitDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSitDownActionPerformed(evt);
            }
        });
        getContentPane().add(btnSitDown);
        btnSitDown.setBounds(560, 600, 154, 39);

        pnlScoreBoard.setOpaque(false);
        pnlScoreBoard.setVisible(false);

        lblScoreBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ScoreBoard.png"))); // NOI18N

        javax.swing.GroupLayout pnlScoreBoardLayout = new javax.swing.GroupLayout(pnlScoreBoard);
        pnlScoreBoard.setLayout(pnlScoreBoardLayout);
        pnlScoreBoardLayout.setHorizontalGroup(
            pnlScoreBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScoreBoardLayout.createSequentialGroup()
                .addComponent(lblScoreBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        pnlScoreBoardLayout.setVerticalGroup(
            pnlScoreBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlScoreBoardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblScoreBoard)
                .addGap(35, 35, 35))
        );

        getContentPane().add(pnlScoreBoard);
        pnlScoreBoard.setBounds(1060, 0, 220, 410);

        pnlBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/login.png"))); // NOI18N
        getContentPane().add(pnlBackground);
        pnlBackground.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if(txtfName.getText().equals("Your name") && String.valueOf(txtfPassword.getPassword()).equals("Password")){
            lblError.setText("Please fill in all the fields.");
            return;
        }
        switch(view.loginProcess(txtfName.getText(),String.valueOf(txtfPassword.getPassword()))){
            case 0: //general error
                lblError.setText("General error.");
                break;
            case 1: //login succeeded
                ImageIcon newIcon = new ImageIcon(getClass().getResource("/resources/bgStandUp.png")); //change
                pnlBackground.setIcon(newIcon);                                                        //background
                pnlLogin.setVisible(false);
                btnSitDown.setVisible(true);
                pnlScoreBoard.setVisible(true);
                lblFactsText.setText("<html>" + view.getFact() + "</html>");
                pnlFacts.setVisible(true);
                view.getCurrentPlayer();
                break;
            case 2: //user already exist & password is incorrect for login
                lblError.setText("Incorrect password.");
                break;
            case 3: //entered name is illegal
                lblError.setText("Illegal name.");
                break;
            default: 
                break;
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtfNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfNameKeyPressed
        if (firstTimeNameType){
           txtfName.setText("");
           txtfName.setForeground(Color.BLACK);
           firstTimeNameType = false;
        }
    }//GEN-LAST:event_txtfNameKeyPressed

    private void txtfPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfPasswordKeyPressed
        if(firstTimePassType){
            txtfPassword.setText("");
            txtfPassword.setForeground(Color.BLACK);
            firstTimePassType = false;
        }
    }//GEN-LAST:event_txtfPasswordKeyPressed

    private void btnSitDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSitDownActionPerformed
        TableFrame tableFrame = new TableFrame(view);      
        tableFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnSitDownActionPerformed

    private void btnSitDownMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSitDownMouseEntered
        btnSitDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/gameButtonHover_SitDown.png")));
    }//GEN-LAST:event_btnSitDownMouseEntered

    private void btnSitDownMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSitDownMouseExited
        btnSitDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/gameButton_SitDown.png")));
    }//GEN-LAST:event_btnSitDownMouseExited

    private void btnSubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseEntered
        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/gameButtonHover_Submit.png")));
    }//GEN-LAST:event_btnSubmitMouseEntered

    private void btnSubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseExited
        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/gameButtonHover_Submit.png")));
    }//GEN-LAST:event_btnSubmitMouseExited

    private void btnSubmitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMousePressed
        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/gameButtonActive_Submit.png")));
    }//GEN-LAST:event_btnSubmitMousePressed

    private void btnSubmitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseReleased
        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/gameButton_Submit.png")));
    }//GEN-LAST:event_btnSubmitMouseReleased

    private void btnSitDownMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSitDownMousePressed
        btnSitDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/gameButtonActive_SitDown.png")));
    }//GEN-LAST:event_btnSitDownMousePressed

    private void btnSitDownMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSitDownMouseReleased
        btnSitDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buttons/gameButton_SitDown.png")));
    }//GEN-LAST:event_btnSitDownMouseReleased

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSitDown;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblBgFacts;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblFactsText;
    private javax.swing.JLabel lblFactsTitle;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblScoreBoard;
    private javax.swing.JLabel pnlBackground;
    private javax.swing.JPanel pnlFacts;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlScoreBoard;
    private javax.swing.JTextField txtfName;
    private javax.swing.JPasswordField txtfPassword;
    // End of variables declaration//GEN-END:variables
}
